# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argoxd < Formula
  desc "Interactive terminal UI for Argo CD"
  homepage "https://github.com/awcodify/argoxd"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/awcodify/argoxd/releases/download/v0.2.0/argoxd_0.2.0_darwin_amd64.tar.gz"
      sha256 "e66bf3663fdc082eb03579e720d9bb4a05eb50176c4ca28e4666dd2649a1c65d"

      define_method(:install) do
        bin.install "argoxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/awcodify/argoxd/releases/download/v0.2.0/argoxd_0.2.0_darwin_arm64.tar.gz"
      sha256 "710ad40b374c246874a88d20da9a41fbdcd8245a65308ed4a6e7a31aeab819f7"

      define_method(:install) do
        bin.install "argoxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/awcodify/argoxd/releases/download/v0.2.0/argoxd_0.2.0_linux_amd64.tar.gz"
      sha256 "6e4dd66418bc2808876b0ab65576881ebadb6fa80abffbfa03177db48a0e1038"
      define_method(:install) do
        bin.install "argoxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awcodify/argoxd/releases/download/v0.2.0/argoxd_0.2.0_linux_arm64.tar.gz"
      sha256 "1f506e777654d15b0110a3a26c65d0d1beee7e9f912bdabec45350e0e5e22e58"
      define_method(:install) do
        bin.install "argoxd"
      end
    end
  end

  test do
    assert_match "Usage of argoxd", shell_output("#{bin}/argoxd -h 2>&1")
  end
end
