# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argoxd < Formula
  desc "Interactive terminal UI for Argo CD"
  homepage "https://github.com/awcodify/argoxd"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/awcodify/argoxd/releases/download/v0.1.0/argoxd_0.1.0_darwin_amd64.tar.gz"
      sha256 "613d202670136f5d4c620dcbd5161fec2ac61218dd84da2b147f3af3dca8007f"

      define_method(:install) do
        bin.install "argoxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/awcodify/argoxd/releases/download/v0.1.0/argoxd_0.1.0_darwin_arm64.tar.gz"
      sha256 "74210a13fc3d542deb80ea40b296d22a9f8031e4b9744d9d4d60dd1739aef2ca"

      define_method(:install) do
        bin.install "argoxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/awcodify/argoxd/releases/download/v0.1.0/argoxd_0.1.0_linux_amd64.tar.gz"
      sha256 "e252d10518b9bfb804b8f2a5233a4e548817c23df42feb139936e8ae58912cff"
      define_method(:install) do
        bin.install "argoxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awcodify/argoxd/releases/download/v0.1.0/argoxd_0.1.0_linux_arm64.tar.gz"
      sha256 "c8e2212a9f7ca9f441fac08c2240d6c7aa494e5c77469bdd15efbf77bea93f44"
      define_method(:install) do
        bin.install "argoxd"
      end
    end
  end

  test do
    assert_match "Usage of argoxd", shell_output("#{bin}/argoxd -h 2>&1")
  end
end
