# This file was generated by GoReleaser. DO NOT EDIT.
cask "argoxd" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "537e87838bde791d7e21ecbee2ee2b5778e2993d8115681dbe2f75427e9bfeb5"
      url "https://github.com/awcodify/argoxd/releases/download/v#{version}/argoxd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "60a36311aa043e0a803b13ad4f031a2462f4aacfe345fa60bd8289f32e4df831"
      url "https://github.com/awcodify/argoxd/releases/download/v#{version}/argoxd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7e96f06c2d00cd649b4784e002362cb5dbfb7fdba53483435a3d4e1e57ad5309"
      url "https://github.com/awcodify/argoxd/releases/download/v#{version}/argoxd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "341bea84c0299d97cc25b8eb383d2d73cd6f2a640361e87cc8e512fdea6e2c7d"
      url "https://github.com/awcodify/argoxd/releases/download/v#{version}/argoxd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "argoxd"
  desc "Interactive terminal UI for Argo CD"
  homepage "https://github.com/awcodify/argoxd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "argoxd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argoxd"]
    end
  end

  # No zap stanza required
end
